### ISSUE TITLE
[epic] JDBC Projections

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#23]
Work has started in #192 

- [x] JdbcSession API (in #192)
- [x] JdbcOffsetStore (in #192)
- [x] Basic JdbcProjection impl (exactly-once) (in #192)
- [x] Dialects: Postgres, MySQL and H2
- [ ] Dialect: MSSQL (in #280)
- [ ] ~Dialect: Oracle~ - postponed to v0.4
- [ ] User defined dialects (nice to have, can be deferred)
- [x] support Recovery Strategy
- [x] support StatusObserver
- [x] support ProjectionManagement
- [x] support for Async Handlers and atLeastOnce
- [x] documentation, including how to define custom JdbcSession (JPA/Hibernate) (in #273)

**Use cases:**

* read from any source and track the offset on a JPA table (transactional and non-transactional )
* read from Akka Persistence journal (Cassandra or JDBC) and track the offset on a JPA table (transactional and non-transactional ). Specialization of the above but since very common we can provide a boilerplate free variant.

**Specs:**

* Offset is managed by a JDBC/JPA table
* needs an offset extraction function to extract the offset from the envelope
For transactional projection, event handlers must be a function (`EntityManager, E) => CompletionStage[Done]` where E is any envelope.
* For non-transactional projection, event handlers can be a function `E => CompletionStage[Done]` where E is any envelope (eg: project to Elastic Search or send a command to an Entity).
* Provide a JPA Offset Store based on Long. When reading Kafka, the offset will be a Long. Other offset types may be supported and can be added when needed (or implemented by user)
* Convenience API when reading from Akka Persistence Journal.
We have a privileged situation when reading from Akka Persistence Journal, as we know how the envelope looks like, we know how to extract the offset (no need for extractor). However, we need a special offset store that knows how to write and read akka.persistence.Offset

**Comment by patriknw** [comment]
I'll give it a try to add the Future based handler

**Comment by patriknw** [comment]
Closing this. MySQL and Oracle are still remaining but we can track those separately (already in progress).
