### ISSUE TITLE
[epic] Slick Projections

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-projection#24]
**Use cases:**

* read from any source and track the offset on a Slick table 
(transactional and non-transactional )
* read from Akka Persistence journal (Cassandra or JDBC) and track the offset on a Slick table (transactional and non-transactional). Specialization of the above but since very common we can provide a boilerplate free variant.

**Specs:**

* Offset is managed by a Slick table
* needs an offset extraction function to extract the offset from the envelope
* Projection event handler is a function `E => DBIO[Done]` where `E` is any envelope. 
Note that differently from JPA, we don't need two APIs because we have `DBIO`.
* Provide a Slick Offset Store based on Long. When reading Kafka, the offset will be a Long. Other offset types may be supported and can be added when needed (or implemented by user)
* Convenience API when reading from Akka Persistence Journal.
We have a privileged situation when reading from Akka Persistence Journal, as we know how the envelope looks like, we know how to extract the offset (no need for extractor). However, we need a special offset store that knows how to write and read akka.persistence.Offset

**Breakdown**:

- [x] support for transactional projections - see PR #35
- [x] support for non-transactional projections (offset buffering / at-least-once) - see PR #69
- [x] Returning Mat value on `Projection.stop` - see #44
- [ ] Consider the introduction of EventHandler trait - see #43
- [x] ~~`ava.sql.Timestamp` for Spanner  - see #41~~ - not part of epic
- [x] Convenience API to integrate with akka-persistence-query API - see #46

**Comment by renatocaval** [comment]
I made it an 'epic' with a todo list to track its evolution.

**Comment by patriknw** [comment]
I'll do "support for non-transactional projections (offset buffering / at-least-once)" now
